<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.shpytchuk</groupId>
    <artifactId>DeRechi</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>DeRechi</name>
    <description>DeRechi microservices</description>

    <modules>
        <module>DB-Postgres</module>
        <module>Discovery</module>
        <module>Getaway</module>
        <module>Client-API</module>
        <module>Admin-API</module>
        <module>Worker</module>
        <module>Notification</module>
<!--        <module>Launcher</module>-->
    </modules>

    <properties>
        <java.version>26</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <spring-cloud.version>2025.1.3</spring-cloud.version>
        <spring-cloud-aws.version>4.1.1</spring-cloud-aws.version>
        <springdoc.version>3.1.0</springdoc.version>
        <notify-hub.version>1.1.0</notify-hub.version>
        <graphql-extended-scalars.version>24.0</graphql-extended-scalars.version>
        <language-detector.version>0.6</language-detector.version>
        <libphonenumber.version>9.0.18</libphonenumber.version>

        <liquibase.version>5.0.4</liquibase.version>
        <liquibase-hibernate.version>5.0.4</liquibase-hibernate.version>

        <jacoco.version>0.8.15</jacoco.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>${spring-cloud-aws.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testcontainers.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.graphql-java</groupId>
                <artifactId>graphql-java-extended-scalars</artifactId>
                <version>${graphql-extended-scalars.version}</version>
            </dependency>

            <dependency>
                <groupId>com.optimaize.languagedetector</groupId>
                <artifactId>language-detector</artifactId>
                <version>${language-detector.version}</version>
            </dependency>

            <dependency>
                <groupId>com.googlecode.libphonenumber</groupId>
                <artifactId>libphonenumber</artifactId>
                <version>${libphonenumber.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.gabrielbbaldez</groupId>
                <artifactId>notify-spring-boot-starter</artifactId>
                <version>${notify-hub.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gabrielbbaldez</groupId>
                <artifactId>notify-email</artifactId>
                <version>${notify-hub.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gabrielbbaldez</groupId>
                <artifactId>notify-telegram</artifactId>
                <version>${notify-hub.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
                <plugin>
                    <groupId>org.liquibase</groupId>
                    <artifactId>liquibase-maven-plugin</artifactId>
                    <version>${liquibase.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <release>${java.version}</release>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${jacoco.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
