query  {
    #    lostItem(id: 2) {
    #        id
    #        category {
    #            id
    #            key
    #        }
    #        contact {
    #            id
    #            email
    #            phone
    #        }
    #        compensation { amount currency }
    #        date
    #        description
    #        image
    #        place {
    #            name
    #            countryCode
    #            lat
    #            lon
    #            id
    #        }
    #        title
    #    }
    lostItems(filter: {near: {lat: 49.8419, lon: 24.0315, radiusKm: 5}})
     {
        edges {
            node {
                id
                category {
                    id
                    key
                }
                contact {
                    id
                    email
                    phone
                }
                compensation { amount currency }
                date
                description
                image
                place {
                    name
                    countryCode
                    lat
                    lon
                    id
                }
                title
            }
        }
        pageInfo  {
            endCursor
            startCursor
        }
    }
}
#
#mutation  {
#    createFoundItem(input: {
#        title: "test"
#        description: "test description"
#        date: "2026-09-12"
#        compensation: { amount: 500 }
#        image: "test"
#        categoryId: 1
#        place: {
#            id: "ChIJq6q6q6q6q6qRq6q6q6q6q6q"
#            name: "Площа Ринок"
#            lat: 49.8419
#            lon: 24.0315
#            countryCode: "UA"
#        }
#        contact: {
#            phone: "+380671234567"
#            email: "test@example.com"
#            socialMedias: [TELEGRAM]
#        }
#    }) {
#        id
#        title
#        description
#        date
#        compensation { amount currency }
#        image
#        category {
#            id
#            key
#        }
#        place {
#            id
#            name
#            lat
#            lon
#        }
#        contact {
#            id
#            phone
#            email
#            socialMedias
#        }
#    }
#}


#
#mutation {
#    createFoundItem(
#        input: {
#            categoryId: 2
#            compensation: { amount: 0, currency: "UAH" }
#            contact: {
#                email: "find@derechi.com"
#                phone: "+38011111111"
#                socialMedias: []
#            }
#            date: "2026-09-07"
#            description: "Знайшов ключі стрийському парку біля лавочки"
#            title: "Ключі стрийський парк"
#            image: "https://sigma.ua/resize_img/nabor-klyuchey-rozhkovo-nakidnykh-treshchotochnykh-8sht-8-10-12-13-14-15-17-19mm-crv-satine-sigma-60_detail_1.jpeg"
#            place: {id: "Стрийськийпарк", lon: 49.8179, lat: 24.00651, name: "Парк", countryCode: "UA"}
#        }
#    ) {
#        id
#        contact {
#            email
#            id
#            phone
#        }
#        description
#        title
#    }
#}
