--liquibase formatted sql

-- changeset vasil:1789241128433-1 splitStatements:false
CREATE TABLE contact_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(50)                             NOT NULL,
    phone         VARCHAR(16)                             NOT NULL,
    social_medias INT2[],
    CONSTRAINT "contact_infoPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-2 splitStatements:false
CREATE TABLE found_item
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compensation          INTEGER,
    date                  date                                    NOT NULL,
    description           VARCHAR(250),
    image                 VARCHAR(200),
    title                 VARCHAR(100)                            NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    info_id               BIGINT                                  NOT NULL,
    place_google_place_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT "found_itemPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-3 splitStatements:false
CREATE TABLE found_item_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compensation          INTEGER,
    date                  date                                    NOT NULL,
    description           VARCHAR(250),
    image                 VARCHAR(200),
    title                 VARCHAR(100)                            NOT NULL,
    archived_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    info_id               BIGINT                                  NOT NULL,
    place_google_place_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT "found_item_historyPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-4 splitStatements:false
CREATE TABLE lost_item
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compensation          INTEGER,
    date                  date                                    NOT NULL,
    description           VARCHAR(250),
    image                 VARCHAR(200),
    title                 VARCHAR(100)                            NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    info_id               BIGINT                                  NOT NULL,
    place_google_place_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT "lost_itemPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-5 splitStatements:false
CREATE TABLE lost_item_history
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compensation          INTEGER,
    date                  date                                    NOT NULL,
    description           VARCHAR(250),
    image                 VARCHAR(200),
    title                 VARCHAR(100)                            NOT NULL,
    archived_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    info_id               BIGINT                                  NOT NULL,
    place_google_place_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT "lost_item_historyPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-6 splitStatements:false
CREATE TABLE place
(
    google_place_id VARCHAR(255)           NOT NULL,
    coordinate      geography(Point,4326)  NOT NULL,
    name            VARCHAR(100)           NOT NULL,
    CONSTRAINT "placePK" PRIMARY KEY (google_place_id)
);

-- changeset vasil:1789241128433-7 splitStatements:false
CREATE TABLE thing_category
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    key VARCHAR(100)                            NOT NULL,
    CONSTRAINT "thing_categoryPK" PRIMARY KEY (id)
);

-- changeset vasil:1789241128433-8 splitStatements:false
ALTER TABLE thing_category
    ADD CONSTRAINT UC_THING_CATEGORYKEY_COL UNIQUE (key);

-- changeset vasil:1789241128433-9 splitStatements:false
ALTER TABLE lost_item
    ADD CONSTRAINT "FK6yioqpc7m1i0yg1mbdwbxun6e" FOREIGN KEY (info_id) REFERENCES contact_info (id);

-- changeset vasil:1789241128433-10 splitStatements:false
ALTER TABLE lost_item_history
    ADD CONSTRAINT "FK70u4k5cj68cb23u7fvdh7nlq5" FOREIGN KEY (info_id) REFERENCES contact_info (id);

-- changeset vasil:1789241128433-11 splitStatements:false
ALTER TABLE found_item_history
    ADD CONSTRAINT "FKapejpe6140stocrjwcq9wb3b" FOREIGN KEY (category_id) REFERENCES thing_category (id);

-- changeset vasil:1789241128433-12 splitStatements:false
ALTER TABLE found_item_history
    ADD CONSTRAINT "FKcs76sy8jr8ypp33h4w402msdk" FOREIGN KEY (place_google_place_id) REFERENCES place (google_place_id);

-- changeset vasil:1789241128433-13 splitStatements:false
ALTER TABLE found_item_history
    ADD CONSTRAINT "FKgle1qi8qlcbop56biww8mcug9" FOREIGN KEY (info_id) REFERENCES contact_info (id);

-- changeset vasil:1789241128433-14 splitStatements:false
ALTER TABLE lost_item_history
    ADD CONSTRAINT "FKhclnxrno7ev3ycck61p9vscxs" FOREIGN KEY (place_google_place_id) REFERENCES place (google_place_id);

-- changeset vasil:1789241128433-15 splitStatements:false
ALTER TABLE found_item
    ADD CONSTRAINT "FKmex47eta3w3naaedje44jd8k6" FOREIGN KEY (category_id) REFERENCES thing_category (id);

-- changeset vasil:1789241128433-16 splitStatements:false
ALTER TABLE lost_item
    ADD CONSTRAINT "FKmh6ft2w76omp60na9ffqtkrmm" FOREIGN KEY (place_google_place_id) REFERENCES place (google_place_id);

-- changeset vasil:1789241128433-17 splitStatements:false
ALTER TABLE found_item
    ADD CONSTRAINT "FKnuj06duc2lxbi2nog3cr8hg1s" FOREIGN KEY (place_google_place_id) REFERENCES place (google_place_id);

-- changeset vasil:1789241128433-18 splitStatements:false
ALTER TABLE lost_item
    ADD CONSTRAINT "FKp24qbicp8qxo1fdvpxiucybt8" FOREIGN KEY (category_id) REFERENCES thing_category (id);

-- changeset vasil:1789241128433-19 splitStatements:false
ALTER TABLE lost_item_history
    ADD CONSTRAINT "FKrto5ucuhr3o58cq45ng73vmkt" FOREIGN KEY (category_id) REFERENCES thing_category (id);

-- changeset vasil:1789241128433-20 splitStatements:false
ALTER TABLE found_item
    ADD CONSTRAINT "FKtd85og5xhg33q75jpviquunmf" FOREIGN KEY (info_id) REFERENCES contact_info (id);

