-- liquibase formatted sql

-- changeset vasil:1789210196619-1 splitStatements:false
CREATE TABLE "contact_info"
(
    "id"            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email"         VARCHAR(50)                             NOT NULL,
    "phone"         VARCHAR(16)                             NOT NULL,
    "social_medias" INT2[],
    CONSTRAINT "contact_infoPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-2 splitStatements:false
CREATE TABLE "found_item"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "compensation" INTEGER,
    "date"         date                                    NOT NULL,
    "description"  VARCHAR(250),
    "title"        VARCHAR(100)                            NOT NULL,
    "image"        VARCHAR(200)                            NOT NULL,
    "category_id"  BIGINT                                  NOT NULL,
    "info_id"      BIGINT                                  NOT NULL,
    "place_id"     BIGINT                                  NOT NULL,
    CONSTRAINT "found_itemPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-3 splitStatements:false
CREATE TABLE "found_item_history"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "compensation" INTEGER,
    "date"         date                                    NOT NULL,
    "description"  VARCHAR(250),
    "title"        VARCHAR(100)                            NOT NULL,
    "archived_at"  TIMESTAMP WITH TIME ZONE                NOT NULL,
    "image"        VARCHAR(200)                            NOT NULL,
    "category_id"  BIGINT                                  NOT NULL,
    "info_id"      BIGINT                                  NOT NULL,
    "place_id"     BIGINT                                  NOT NULL,
    CONSTRAINT "found_item_historyPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-4 splitStatements:false
CREATE TABLE "lost_item"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "compensation" INTEGER,
    "date"         date                                    NOT NULL,
    "description"  VARCHAR(250),
    "title"        VARCHAR(100)                            NOT NULL,
    "image"        VARCHAR(200),
    "category_id"  BIGINT                                  NOT NULL,
    "info_id"      BIGINT                                  NOT NULL,
    "place_id"     BIGINT                                  NOT NULL,
    CONSTRAINT "lost_itemPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-5 splitStatements:false
CREATE TABLE "lost_item_history"
(
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "compensation" INTEGER,
    "date"         date                                    NOT NULL,
    "description"  VARCHAR(250),
    "title"        VARCHAR(100)                            NOT NULL,
    "archived_at"  TIMESTAMP WITH TIME ZONE                NOT NULL,
    "image"        VARCHAR(200),
    "category_id"  BIGINT                                  NOT NULL,
    "info_id"      BIGINT                                  NOT NULL,
    "place_id"     BIGINT                                  NOT NULL,
    CONSTRAINT "lost_item_historyPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-6 splitStatements:false
CREATE TABLE "thing_category"
(
    "id"  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "key" VARCHAR(100)                            NOT NULL,
    CONSTRAINT "thing_categoryPK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-7 splitStatements:false
ALTER TABLE "thing_category"
    ADD CONSTRAINT "uc_thing_categorykey_col" UNIQUE ("key");

-- changeset vasil:1789210196619-8 splitStatements:false
CREATE TABLE "place"
(
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "coordinate" geography(Point,4326) NOT NULL,
    "name"       VARCHAR(100)                            NOT NULL,
    CONSTRAINT "placePK" PRIMARY KEY ("id")
);

-- changeset vasil:1789210196619-9 splitStatements:false
ALTER TABLE "lost_item_history"
    ADD CONSTRAINT "FK3uayixyiku40yc6qbv3q0qcr7" FOREIGN KEY ("place_id") REFERENCES "place" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-10 splitStatements:false
ALTER TABLE "lost_item"
    ADD CONSTRAINT "FK6yioqpc7m1i0yg1mbdwbxun6e" FOREIGN KEY ("info_id") REFERENCES "contact_info" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-11 splitStatements:false
ALTER TABLE "lost_item_history"
    ADD CONSTRAINT "FK70u4k5cj68cb23u7fvdh7nlq5" FOREIGN KEY ("info_id") REFERENCES "contact_info" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-12 splitStatements:false
ALTER TABLE "lost_item"
    ADD CONSTRAINT "FK8qo4sda58274gf6bx1mjsj11s" FOREIGN KEY ("place_id") REFERENCES "place" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-13 splitStatements:false
ALTER TABLE "found_item_history"
    ADD CONSTRAINT "FKapejpe6140stocrjwcq9wb3b" FOREIGN KEY ("category_id") REFERENCES "thing_category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-14 splitStatements:false
ALTER TABLE "found_item"
    ADD CONSTRAINT "FKb338fxg1v1899aysut3u4sm7p" FOREIGN KEY ("place_id") REFERENCES "place" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-15 splitStatements:false
ALTER TABLE "found_item_history"
    ADD CONSTRAINT "FKgle1qi8qlcbop56biww8mcug9" FOREIGN KEY ("info_id") REFERENCES "contact_info" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-16 splitStatements:false
ALTER TABLE "found_item_history"
    ADD CONSTRAINT "FKlhkyihbyxea19k6d25agcinch" FOREIGN KEY ("place_id") REFERENCES "place" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-17 splitStatements:false
ALTER TABLE "found_item"
    ADD CONSTRAINT "FKmex47eta3w3naaedje44jd8k6" FOREIGN KEY ("category_id") REFERENCES "thing_category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-18 splitStatements:false
ALTER TABLE "lost_item"
    ADD CONSTRAINT "FKp24qbicp8qxo1fdvpxiucybt8" FOREIGN KEY ("category_id") REFERENCES "thing_category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-19 splitStatements:false
ALTER TABLE "lost_item_history"
    ADD CONSTRAINT "FKrto5ucuhr3o58cq45ng73vmkt" FOREIGN KEY ("category_id") REFERENCES "thing_category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset vasil:1789210196619-20 splitStatements:false
ALTER TABLE "found_item"
    ADD CONSTRAINT "FKtd85og5xhg33q75jpviquunmf" FOREIGN KEY ("info_id") REFERENCES "contact_info" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

