-- liquibase formatted sql

-- changeset vasil:006-item-claims-1 splitStatements:false
CREATE TABLE lost_item_claim
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lost_item_id         BIGINT                                  NOT NULL,
    contact_info_id      BIGINT                                  NOT NULL,
    token                VARCHAR(36)                             NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    author_reminded_at   TIMESTAMP(6) WITH TIME ZONE,
    claimant_reminded_at TIMESTAMP(6) WITH TIME ZONE,
    confirmed_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT "lost_item_claimPK" PRIMARY KEY (id),
    CONSTRAINT lost_item_claim_token_uq UNIQUE (token)
);

-- changeset vasil:006-item-claims-2 splitStatements:false
CREATE TABLE found_item_claim
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    found_item_id        BIGINT                                  NOT NULL,
    contact_info_id      BIGINT                                  NOT NULL,
    token                VARCHAR(36)                             NOT NULL,
    created_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    author_reminded_at   TIMESTAMP(6) WITH TIME ZONE,
    claimant_reminded_at TIMESTAMP(6) WITH TIME ZONE,
    confirmed_at         TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT "found_item_claimPK" PRIMARY KEY (id),
    CONSTRAINT found_item_claim_token_uq UNIQUE (token)
);

-- changeset vasil:006-item-claims-3 splitStatements:false
ALTER TABLE lost_item_claim
    ADD CONSTRAINT lost_item_claim_item_fk FOREIGN KEY (lost_item_id) REFERENCES lost_item (id);
ALTER TABLE lost_item_claim
    ADD CONSTRAINT lost_item_claim_contact_fk FOREIGN KEY (contact_info_id) REFERENCES contact_info (id);
CREATE INDEX lost_item_claim_item_idx ON lost_item_claim (lost_item_id);

-- changeset vasil:006-item-claims-4 splitStatements:false
ALTER TABLE found_item_claim
    ADD CONSTRAINT found_item_claim_item_fk FOREIGN KEY (found_item_id) REFERENCES found_item (id);
ALTER TABLE found_item_claim
    ADD CONSTRAINT found_item_claim_contact_fk FOREIGN KEY (contact_info_id) REFERENCES contact_info (id);
CREATE INDEX found_item_claim_item_idx ON found_item_claim (found_item_id);
