-- liquibase formatted sql

-- changeset vasil:007-claim-payment-1 splitStatements:false
ALTER TABLE lost_item_claim
    ADD COLUMN payment_product_id VARCHAR(64),
    ADD COLUMN payment_variant_id VARCHAR(64),
    ADD COLUMN paid_at            TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN contacts_sent_at   TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE found_item_claim
    ADD COLUMN payment_product_id VARCHAR(64),
    ADD COLUMN payment_variant_id VARCHAR(64),
    ADD COLUMN paid_at            TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN contacts_sent_at   TIMESTAMP(6) WITH TIME ZONE;

ALTER TABLE lost_item_claim
    ADD CONSTRAINT lost_item_claim_payment_variant_id_uq UNIQUE (payment_variant_id);
ALTER TABLE found_item_claim
    ADD CONSTRAINT found_item_claim_payment_variant_id_uq UNIQUE (payment_variant_id);

-- changeset vasil:007-claim-payment-2 splitStatements:false
CREATE TABLE fourthwall_order
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id            VARCHAR(64)                             NOT NULL,
    friendly_id         VARCHAR(64),
    status              VARCHAR(40)                             NOT NULL,
    email               VARCHAR(100),
    username            VARCHAR(100),
    amount              NUMERIC(10, 2)                          NOT NULL,
    currency            VARCHAR(3)                              NOT NULL,
    test_mode           BOOLEAN                                 NOT NULL,
    placed_at           TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    received_at         TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    lost_item_claim_id  BIGINT,
    found_item_claim_id BIGINT,
    CONSTRAINT "fourthwall_orderPK" PRIMARY KEY (id),
    CONSTRAINT fourthwall_order_order_id_uq UNIQUE (order_id)
);

-- changeset vasil:007-claim-payment-3 splitStatements:false
ALTER TABLE fourthwall_order
    ADD CONSTRAINT fourthwall_order_lost_item_claim_fk FOREIGN KEY (lost_item_claim_id) REFERENCES lost_item_claim (id) ON DELETE SET NULL;
ALTER TABLE fourthwall_order
    ADD CONSTRAINT fourthwall_order_found_item_claim_fk FOREIGN KEY (found_item_claim_id) REFERENCES found_item_claim (id) ON DELETE SET NULL;
CREATE INDEX fourthwall_order_lost_item_claim_idx ON fourthwall_order (lost_item_claim_id);
CREATE INDEX fourthwall_order_found_item_claim_idx ON fourthwall_order (found_item_claim_id);
