
changeLogFile=changelog/changelog-master.yaml

url=jdbc:postgresql://localhost:5432/derechi
username=derechi
password=derechi

diffChangeLogFile=DB-Postgres/changelog/changes/003-delta.postgresql.sql

referenceUrl=hibernate:spring:org.shpytchuk.dbpostgres?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

diffExcludeObjects=(?i)spatial_ref_sys,geography_columns,geometry_columns,raster_columns,raster_overviews
