spring:
  application:
    name: DB-Postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/derechi
    username: derechi
    password: derechi

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog-master.yaml
